### ISSUE TITLE
Proposition to add encryption of volumes for EKS Worker Nodes

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [cloudposse/terraform-aws-eks-workers#11]
I have code to add to this module that will create kms key with needed policies and creation of new ami with encryption of volumes, i can create PR to add this possibility to this module but not sure if its necessary because this can be done outside of module. @aknysh will this need for future use or useless for now?

**Comment by aknysh** [comment]
@dmitriy-lukyanchikov 
the functionality you described is definitely outside the scope of this module (not it's concern).
But it would be nice to add everything you described in the examples:

https://github.com/cloudposse/terraform-aws-eks-workers/tree/master/examples/complete
https://github.com/cloudposse/terraform-aws-eks-cluster/tree/master/examples/complete

would show people how to create and use custom AMIs to use for EKs workers, would be very informative.

Thanks

**Comment by dmitriy-lukyanchikov** [comment]
ok, sounds good

**Comment by aknysh** [comment]
will close for now
