### ISSUE TITLE
Add ability to configure host node volume size.

### ISSUE THREAD

**Issue by ewhal** [cloudposse/terraform-aws-eks-workers#16]
By default the host volume size is 20gb which can be a bit lacking especially with larger machines.

I can make a pr if you'd like

**Comment by aknysh** [comment]
@ewhal thanks!
Are you talking about https://www.terraform.io/docs/providers/aws/r/launch_template.html#block_device_mappings?

If yes, then it's supported:
https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/blob/master/main.tf#L17
https://github.com/cloudposse/terraform-aws-eks-workers/blob/master/main.tf#L201

If it's something else, PRs are very welcome.
Thanks

**Comment by aknysh** [comment]
@ewhal  thanks again, will close for now, please reopen if you still have the issue

**Comment by CodechCFA** [comment]
Configuring block device mappings doesn't seem to be working for me.

This configuration
```
block_device_mappings                  = [{
    virtual_name = "ephemeral0"
    device_name = "/dev/xvda"
    no_device = false
    ebs = {
      delete_on_termination = true
      volume_size = 50
      volume_type = "gp2"
      encrypted = false
    }
  }]
```
Gives me the following error:
```
attribute "ebs": attributes "iops", "kms_key_id", and "snapshot_id" are required.
```

If I give those attributes empty values and set the iops to 100, then my autoscaling groups don't work. They fail to scale new instances with the following error: 

`The parameter iops is not supported for gp2 volumes. Launching EC2 instance failed.`

**Comment by CodechCFA** [comment]
@aknysh any idea? Love this module so I'd love to get this working.

**Comment by aknysh** [comment]
@CodechCFA 

Take a look https://www.terraform.io/docs/configuration/expressions.html

```
null: a value that represents absence or omission. If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory
```

You can set all those attributes that are not used in your particular setup to `null` and terraform will behave as if they were not specified at all.

**Comment by CodechCFA** [comment]
Ah that does work thanks @aknysh . Everything I saw in the terraform docs with block device mappings just omitted the fields that weren't needed so figured this would have worked the same way.
