### ISSUE TITLE
do we plan to add node groups ?

### ISSUE THREAD

**Issue by amitsehgal** [cloudposse/terraform-aws-eks-workers#30]

**Comment by aknysh** [comment]
@amitsehgal 

https://github.com/cloudposse/terraform-aws-eks-node-group
https://github.com/cloudposse/terraform-aws-eks-node-group/tree/master/examples/complete

https://github.com/cloudposse/terraform-aws-eks-fargate-profile
https://github.com/cloudposse/terraform-aws-eks-fargate-profile/tree/master/examples/complete

The EKS cluster module https://github.com/cloudposse/terraform-aws-eks-cluster
can work with any of these
https://github.com/cloudposse/terraform-aws-eks-workers
https://github.com/cloudposse/terraform-aws-eks-node-group
https://github.com/cloudposse/terraform-aws-eks-fargate-profile

Also it's possible to use any combination of the three worker modules together in one cluster, for example
https://github.com/cloudposse/terraform-aws-eks-fargate-profile/blob/master/examples/complete/main.tf

**Comment by amitsehgal** [comment]
Thanks - closing this issue
