### ISSUE TITLE
Deployment commands 

### ISSUE THREAD

**Issue by ismailyenigul** [cloudposse/terraform-aws-eks-workers#38]
First thanks for your terraform modules. They are really useful and make devops life easier.
If you can add full deployment commands into each repo, it might be better for newcomers.
like
```
$ git clone to specific tag
$ cd samples/directory
$ vi fixtures.us-east-2.tfvars
$ export AWS_ACCESS_KEY_ID="xyz"
$ export AWS_SECRET_ACCESS_KEY="abc"
$ export AWS_DEFAULT_REGION="us-west-2"
$ terraform plan

```
Thanks

**Comment by Gowiem** [comment]
@ismailyenigul We expect folks to know how to do these things as they're inherently required knowledge for using Terraform + the AWS Provider. Going to close out as I can't see us adding these types of instructions right now.
