### ISSUE TITLE
Latest image regex doesn't seem to be working

### ISSUE THREAD

**Issue by tthayer** [cloudposse/terraform-aws-eks-workers#40]
I have found that the regex match doesn't seem to be working for finding the latest image and as a result the nodes that come up are for 1.13 despite my building a cluster using 1.16.

Playing around with the regex search I found this should work instead:
`amazon-eks-node-[1-9]\.[1-9]{2}-v\d{8}`

Has anyone else been having this issue?

**Comment by Gowiem** [comment]
@tthayer I don't see anyone else has run into this... Is this still an issue you think needs to get addressed or are we good to close this out?

**Comment by tthayer** [comment]
We overrode it and now are using our own images so I can't speak to it still being an issue for anyone else.
