### ISSUE TITLE
Conflicting AWS Provider versions between modules

### ISSUE THREAD

**Issue by dotCipher** [cloudposse/terraform-aws-eks-workers#46]
## Describe the Bug

If I happen to use this module with [cloudposse/terraform-aws-eks-node-group](https://github.com/cloudposse/terraform-aws-eks-node-group) I get a conflicting provider error for aws.

When running `terraform init -backend=false .` on the related terraform:
```
Initializing provider plugins...
- Using previously-installed hashicorp/null v2.1.2
- Using previously-installed hashicorp/local v1.4.0
- Using previously-installed hashicorp/kubernetes v1.12.0
- Using previously-installed hashicorp/template v2.1.2
- Finding hashicorp/aws versions matching ">= 2.0.*, < 4.0.*, ~> 3.0, >= 2.0.*, < 4.0.*, >= 2.0.*, < 4.0.*, ~> 2.0, ~> 2.0"...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
no available releases match the given constraints >= 2.0.*, < 4.0.*, ~> 3.0,
>= 2.0.*, < 4.0.*, >= 2.0.*, < 4.0.*, ~> 2.0, ~> 2.0
```

FWIW, this output includes module boundaries from a few other cloudposse modules (like [terraform-aws-dynamic-subnets](github.com/cloudposse/terraform-aws-dynamic-subnets), [terraform-aws-vpc](github.com/cloudposse/terraform-aws-vpc), etc)

## Expected Behavior

I should be able to get all providers

## Steps to Reproduce:
1. Create `.tf` with module usage of both [cloudposse/terraform-aws-eks-node-group](https://github.com/cloudposse/terraform-aws-eks-node-group) and this module using the latest versions of both as of writing this (`0.10.0` and `0.15.2` respectively)
1. Run `terraform init -backend=false .`
1. See error output

## Environment:

 - OS: OSX
 - Version 10.15.6

Output of `terraform -version` within terraform dir:
```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/template v2.1.2
```

**Comment by dotCipher** [comment]
After https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/32 is merged, this repo will probably need to bump versions as well to resolve this issue

**Comment by tsunamishaun** [comment]
Also hitting `required_version` issues between modules, bumping 
https://github.com/cloudposse/terraform-aws-eks-workers/blob/master/main.tf#L171 to `v0.7.4` should fix.

**Comment by Nuru** [comment]
This should be fixed now that we have removed upper bounds on all providers in all Cloud Posse Terraform modules.
