### ISSUE TITLE
Feature request: ability to pass in aws-auth roles/users

### ISSUE THREAD

**Issue by philwinder** [cloudposse/terraform-aws-eks-workers#5]
I would like the ability to pass in extra roles and/or users to be templated in the `aws-auth` template. 

See https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/aws_auth.tf for an example.

**Comment by aknysh** [comment]
@philwinder 
thank you, we can add the roles, or if you want to open a PR, it will be promptly reviewed!

**Comment by osulli** [comment]
@gramidt & @philwinder this has now been implemented.

I'm going to close this as I'm confident it has been covered, but please re-open if I am incorrect.
