### ISSUE TITLE
"list" function was deprecated in Terraform v0.12 and is no longer available

### ISSUE THREAD

**Issue by Nightbr** [cloudposse/terraform-aws-eks-workers#66]
Hello, 

thanks for all your Terraform modules :ok_hand:

## Describe the Bug

Seems there is a change in come function Terraform handles. It was a warning but now if you upgrade to tf 0.15.0 it will throw an error.

```
╷
│ Error: Error in function call
│ 
│   on .terraform/modules/eks_workers.autoscale_group/main.tf line 14, in resource "aws_launch_template" "default":
│   14:         for_each = flatten(list(lookup(block_device_mappings.value, "ebs", [])))
│     ├────────────────
│     │ block_device_mappings.value will be known only after apply
│ 
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.
```

## Expected Behavior

We should handle properly new terraform function such as tolist instead of legacy list function:

https://www.terraform.io/docs/language/functions/list.html

## Steps to Reproduce
2. Run '....'
3. Enter '....'

## Screenshots

![image](https://user-images.githubusercontent.com/4228646/115866192-a0097e80-a439-11eb-9849-e71918c504e3.png)

## Environment (please complete the following information):

 - OS: Linux Mint (ubuntu base)
 - Version terraform v0.15.0

## Additional Context

Here my fix: 
`for_each = flatten(tolist([lookup(block_device_mappings.value, "ebs", [])]))`

Seems to work so far.

Related https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/issues/64

Feel free to ask me anything to help tackle this :ok_hand:

**Comment by Nuru** [comment]
Closed by #67
