### ISSUE TITLE
default `eks_worker_ami_name_regex` should be updated to handle 1.20

### ISSUE THREAD

**Issue by Nightbr** [cloudposse/terraform-aws-eks-workers#71]
Hey, I just found a simple bug when you want to use EKS with kubernetes 1.20 the AMI is not found.

## Describe the Bug

Set `kubernetes_version` to 1.20

```
╷
│ Error: "name_regex": error parsing regexp: missing argument to repetition operator: `*`
│ 
│   with module.eks_workers.data.aws_ami.eks_worker[0],
│   on .terraform/modules/eks_workers/main.tf line 139, in data "aws_ami" "eks_worker":
│  139:   name_regex  = var.eks_worker_ami_name_regex
│ 
╵
```

## Solution

Just need to change `eks_worker_ami_name_regex  = "^amazon-eks-node-[0-9,.]+-v[0-9]{8}$"` as the default regexp.

## Workaround

We can pass the parameters eks_worker_ami_name_regex  = "^amazon-eks-node-[0-9,.]+-v[0-9]{8}$" to the module directly.

**Comment by arischow** [comment]
Mine: `^amazon-eks-node-[0-9]+\\.[0-9]+-v[0-9]{8}$`
